[languages]
  php = { version = "8.1" }

[phases.setup]
  nixPkgs = [
    "php",
    "php81Packages.composer",
    "nodejs",
    "npm",
    "pkg-config",
    "openssl",
    "autoconf",
    "bzip2",
    "curl",
    "libjpeg",
    "libpng",
    "libwebp",
    "libxml2",
    "libzip",
    "zlib",
    "php81Extensions.pdo",
    "php81Extensions.pdo_mysql",
    "php81Extensions.mbstring",
    "php81Extensions.tokenizer",
    "php81Extensions.xml",
    "php81Extensions.curl",
    "php81Extensions.fileinfo",
    "php81Extensions.zip",
  ]

[phases.build]
  run = [
    "composer install --optimize-autoloader --no-dev",
    "npm install",
    "npm run build",
    "php artisan config:cache",
    "php artisan route:cache",
    "php artisan view:cache"
  ]

[phases.start]
  run = "php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=${PORT:-8080}"
